backend:
  name: github
  repo: lindakatcodes/lindakat-blogs

media_folder: "static/uploads"
public_folder: "/uploads"

publish_mode: editorial_workflow

collections:
  - name: "posts"
    label: "Posts"
    folder: "posts"
    create: true
    slug: "{{slug}}"
    fields: 
      - {label: "Publish Date", name: "date", widget: "date"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Post Blurb", name: "description", widget: "string"}
      - {label: "Tags", name: "tags", widget: "list"}
      - {label: "Body", name: "body", widget: "markdown"}